# Generated by Django 5.0.3 on 2024-03-08 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_name', models.CharField(max_length=255)),
                ('law_exp', models.IntegerField()),
                ('law_edu', models.TextField()),
                ('law_image', models.ImageField(upload_to='lawyers')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
        ),
    ]
