# Generated by Django 5.0.3 on 2024-03-10 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lawyers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_address', models.TextField()),
                ('c_state', models.CharField(max_length=255)),
                ('C_city', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
                ('law_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lawyers')),
            ],
        ),
    ]
